// Generates the layered scenery in assets/scene/ and the scene markup in index.html.
// Run from anywhere with: node tools/gen-scene.mjs   (every layer shares one 2560x1440 canvas)
//
// Three scenes per theme, five layers each (sky, far, mid, near, front), named like night-2-mid.svg.
// Swapping in your own art: put a file with the same name and any image extension (night-2-mid.webp)
// in assets/scene/. The markup always uses whatever file exists for a layer, preferring a raster
// (webp, avif, png, jpg) over an SVG, and the generator never overwrites an SVG it did not write.
// Rasters should be 16:9 (2560x1440 is plenty) and transparent everywhere except in the sky layer.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(REPO, "assets/scene");
fs.mkdirSync(OUT, { recursive: true });

const W = 2560, H = 1440;
const MARK = "<!-- generated by tools/gen-scene.mjs -->";
const RASTER = ["webp", "avif", "png", "jpg", "jpeg"];

// The middle of the canvas is where the page's text sits, so the art frames it: tall things hug
// the sides (x < ~480, x > ~2080), the ground stays in the bottom fifth, and only soft sky, mist
// and the odd stray branch cross the middle.

function rng(seed) {
  return function () {
    seed |= 0; seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const f = (n) => +n.toFixed(1);
const pick = (r, arr) => arr[Math.floor(r() * arr.length)];
const lerp = (a, b, t) => a + (b - a) * t;
const pt = (p) => `${f(p[0])},${f(p[1])}`;

function wave(r, y, amps, step = 16, x0 = -120, x1 = W + 120) {
  const comps = amps.map(([a, wl]) => ({ a, k: (2 * Math.PI) / wl, p: r() * Math.PI * 2 }));
  const pts = [];
  for (let x = x0; x <= x1; x += step) {
    let yy = y;
    for (const c of comps) yy += c.a * Math.sin(c.k * x + c.p);
    pts.push([x, yy]);
  }
  return pts;
}

// Midpoint displacement: turns a few key points into a rough, natural outline.
function displace(r, keys, rough = 0.13, depth = 6) {
  let pts = keys.slice();
  for (let d = 0; d < depth; d++) {
    const out = [pts[0]];
    for (let i = 1; i < pts.length; i++) {
      const [ax, ay] = pts[i - 1], [bx, by] = pts[i];
      const len = Math.hypot(bx - ax, by - ay);
      out.push([(ax + bx) / 2 + (r() - 0.5) * len * rough, (ay + by) / 2 + (r() - 0.5) * len * rough * 2]);
      out.push(pts[i]);
    }
    pts = out;
  }
  return pts;
}

const area = (pts, bottom = H + 40) => `M${f(pts[0][0])},${bottom}L` + pts.map(pt).join("L") + `L${f(pts.at(-1)[0])},${bottom}Z`;
const line = (pts) => "M" + pts.map(pt).join("L");
const poly = (pts) => "M" + pts.map(pt).join("L") + "Z";
const box = (x, y, w, h) => `M${f(x)},${f(y)}h${f(w)}v${f(h)}h${f(-w)}Z`;
const circle = (x, y, r) => `M${f(x - r)},${f(y)}a${f(r)},${f(r)} 0 1,0 ${f(2 * r)},0a${f(r)},${f(r)} 0 1,0 ${f(-2 * r)},0`;

// An ellipse as path data, optionally turned by `rot` radians (so many can share one <path>).
function oval(x, y, rx, ry, rot = 0) {
  const c = Math.cos(rot) * rx, s = Math.sin(rot) * rx, deg = f((rot * 180) / Math.PI);
  return `M${f(x - c)},${f(y - s)}a${f(rx)},${f(ry)} ${deg} 1,0 ${f(2 * c)},${f(2 * s)}a${f(rx)},${f(ry)} ${deg} 1,0 ${f(-2 * c)},${f(-2 * s)}`;
}

function yAt(pts, x) {
  for (let i = 1; i < pts.length; i++) {
    if (pts[i][0] >= x) {
      const [ax, ay] = pts[i - 1], [bx, by] = pts[i];
      return ay + ((by - ay) * (x - ax)) / (bx - ax || 1);
    }
  }
  return pts.at(-1)[1];
}

// Points along a quadratic bezier.
function quad(a, c, b, n = 24) {
  return Array.from({ length: n + 1 }, (_, i) => {
    const t = i / n, u = 1 - t;
    return [u * u * a[0] + 2 * u * t * c[0] + t * t * b[0], u * u * a[1] + 2 * u * t * c[1] + t * t * b[1]];
  });
}

// A filled stroke along a polyline that narrows from w0 to w1 (trunks, stalks, branches).
function taper(pts, w0, w1) {
  const L = [], R = [];
  pts.forEach((p, i) => {
    const q = pts[Math.min(i + 1, pts.length - 1)], o = pts[Math.max(i - 1, 0)];
    const dx = q[0] - o[0], dy = q[1] - o[1], d = Math.hypot(dx, dy) || 1;
    const w = lerp(w0, w1, i / (pts.length - 1)) / 2;
    L.push([p[0] - (dy / d) * w, p[1] + (dx / d) * w]);
    R.push([p[0] + (dy / d) * w, p[1] - (dx / d) * w]);
  });
  return poly(L.concat(R.reverse()));
}

// A pointed leaf from (x, y) in direction a.
function leafPath(x, y, a, len, wid, bow = 0) {
  const ex = x + Math.cos(a) * len, ey = y + Math.sin(a) * len;
  const nx = -Math.sin(a), ny = Math.cos(a), mx = (x + ex) / 2 + nx * bow, my = (y + ey) / 2 + ny * bow;
  return `M${f(x)},${f(y)}Q${f(mx + nx * wid)},${f(my + ny * wid)} ${f(ex)},${f(ey)}Q${f(mx - nx * wid)},${f(my - ny * wid)} ${f(x)},${f(y)}Z`;
}

function maple(x, y, s, rot) {
  const pts = [];
  for (let i = 0; i < 10; i++) {
    const a = rot - Math.PI / 2 + (i * Math.PI) / 5;
    const rr = i % 2 ? s * 0.42 : s * (i === 4 || i === 6 ? 0.72 : 1);
    pts.push([x + Math.cos(a) * rr, y + Math.sin(a) * rr]);
  }
  return poly(pts);
}

function blade(x, base, h, w, bend) {
  return `M${f(x - w)},${f(base)}Q${f(x - w * 0.5 + bend * 0.5)},${f(base - h * 0.5)} ${f(x + bend)},${f(base - h)}Q${f(x + w * 0.5 + bend * 0.5)},${f(base - h * 0.5)} ${f(x + w)},${f(base)}Z`;
}

function grass(r, n, x0, x1, base, h, w = 2.4) {
  let d = "";
  for (let i = 0; i < n; i++) {
    const x = lerp(x0, x1, r()), b = base + r() * 14;
    for (let k = 0; k < 5; k++) d += blade(x + (r() - 0.5) * 18, b, h * (0.4 + r() * 0.8), w, (r() - 0.5) * h * 0.7);
  }
  return d;
}

// Bends angle a toward the direction (tx, ty) by k (0..1).
function steer(a, tx, ty, k) {
  return Math.atan2(Math.sin(a) * (1 - k) + ty * k, Math.cos(a) * (1 - k) + tx * k);
}

// A branching tree: returns the wood as one path and the branch ends (where foliage goes).
// o.up pulls branches skyward, o.flat pulls them level (Japanese pines).
function growTree(r, x, y, a, len, w, depth, o = {}) {
  const spread = o.spread ?? 0.5, shrink = o.shrink ?? 0.72, leafDepth = o.leafDepth ?? 2;
  let wood = "";
  const tips = [];
  (function grow(x, y, a, len, w, d) {
    const ex = x + Math.cos(a) * len, ey = y + Math.sin(a) * len;
    const bend = (r() - 0.5) * len * 0.35;
    const c = [(x + ex) / 2 - Math.sin(a) * bend, (y + ey) / 2 + Math.cos(a) * bend];
    const w2 = Math.max(w * shrink, 1.4);
    wood += taper(quad([x, y], c, [ex, ey], 6), w, w2);
    if (d <= leafDepth) tips.push([ex, ey]);
    if (d === 0) return;
    const n = r() < (o.fork3 ?? 0.3) ? 3 : 2;
    for (let k = 0; k < n; k++) {
      const off = n === 2 ? (k ? 1 : -1) * spread * (0.6 + r() * 0.6) : (k - 1) * spread * (0.8 + r() * 0.4);
      let na = a + off + (r() - 0.5) * 0.3;
      if (o.up) na = steer(na, 0, -1, o.up);
      if (o.flat) na = steer(na, Math.cos(na) >= 0 ? 1 : -1, -0.12, o.flat);
      if (o.lean) na = steer(na, o.lean[0], o.lean[1], o.lean[2]);
      grow(ex, ey, na, len * (0.68 + r() * 0.2), w2, d - 1);
    }
  })(x, y, a, len, w, depth);
  return { wood, tips };
}

// A leafy clump: a blob whose edge is scalloped into soft lobes.
function clump(r, x, y, rr, squash = 1) {
  const n = 2 * (5 + Math.floor(r() * 4)), pts = [], a0 = r() * Math.PI;
  for (let i = 0; i < n; i++) {
    const a = a0 + ((i + (r() - 0.5) * 0.7) / n) * Math.PI * 2, k = rr * (i % 2 ? 0.68 + r() * 0.2 : 0.92 + r() * 0.3);
    pts.push([x + Math.cos(a) * k, y + Math.sin(a) * k * squash]);
  }
  const mid = (i) => {
    const p = pts[i % n], q = pts[(i + 1) % n];
    return [(p[0] + q[0]) / 2, (p[1] + q[1]) / 2];
  };
  let d = `M${pt(mid(0))}`;
  for (let i = 1; i <= n; i++) d += `Q${pt(pts[i % n])} ${pt(mid(i))}`;
  return d + "Z";
}

// Foliage around branch ends, in four tones: shadow, body, lit side, and loose specks/petals.
// `light` points toward the light source; `squash` flattens clumps into pine-like pads.
function canopy(r, tips, size, tones, o = {}) {
  const light = o.light ?? [0.6, -0.8], squash = o.squash ?? 1, specks = o.specks ?? 0, shape = o.shape;
  const d = ["", "", "", ""], seen = new Set();
  for (const [x, y] of tips) {
    const cell = `${Math.round(x / (size * 0.8))},${Math.round(y / (size * 0.8))}`;
    if (seen.has(cell)) continue;
    seen.add(cell);
    const n = 2 + Math.floor(r() * 2);
    for (let k = 0; k < n; k++) {
      const rr = size * (0.5 + r() * 0.6), px = x + (r() - 0.5) * size * 1.8, py = y + (r() - 0.5) * size * squash;
      d[0] += clump(r, px - light[0] * rr * 0.12, py + rr * 0.2 * squash, rr * 1.08, squash);
      d[1] += clump(r, px, py, rr * 0.86, squash);
      if (r() < 0.55) d[2] += clump(r, px + light[0] * rr * 0.34, py + light[1] * rr * 0.34 * squash, rr * 0.42, squash);
    }
    for (let k = 0; k < specks; k++) {
      const a = r() * Math.PI * 2, dist = size * (0.9 + r() * 1.2);
      const sx = x + Math.cos(a) * dist * 1.3, sy = y + Math.sin(a) * dist * 0.8 * squash;
      d[3] += shape ? shape(sx, sy, 3 + r() * 5, r() * 6) : oval(sx, sy, 3 + r() * 3, 1.6 + r() * 1.4, r() * 3);
    }
  }
  return d.map((p, i) => (p ? `<path d="${p}" fill="${tones[i]}"/>` : "")).join("");
}

// A rough rock from a closed outline of key points; returns the outline points.
function rock(r, keys, rough = 0.14, depth = 5) {
  return displace(r, keys, rough, depth);
}

// One upturned temple roof, eaves at y.
function roof(cx, y, w, h) {
  const e = w / 2;
  return `M${f(cx - e)},${f(y - h * 0.4)}Q${f(cx - e * 0.86)},${f(y)} ${f(cx - e * 0.7)},${f(y)}L${f(cx + e * 0.7)},${f(y)}` +
    `Q${f(cx + e * 0.86)},${f(y)} ${f(cx + e)},${f(y - h * 0.4)}Q${f(cx + e * 0.45)},${f(y - h * 0.5)} ${f(cx + e * 0.2)},${f(y - h)}` +
    `L${f(cx - e * 0.2)},${f(y - h)}Q${f(cx - e * 0.45)},${f(y - h * 0.5)} ${f(cx - e)},${f(y - h * 0.4)}Z`;
}

// A tiered pagoda; returns the silhouette and its lit windows as [x, y, w, h].
function pagoda(r, cx, base, w, tiers, s) {
  let body = "";
  const lights = [];
  let y = base, tw = w;
  for (let t = 0; t < tiers; t++) {
    const wallH = s * (t === 0 ? 1.05 : 0.7), bw = tw * 0.52;
    body += box(cx - bw / 2, y - wallH, bw, wallH + 2) + box(cx - bw * 0.62, y - wallH * 0.12, bw * 1.24, s * 0.07);
    const n = Math.max(1, Math.round(bw / (s * 0.55)));
    for (let k = 0; k < n; k++) {
      if (r() < 0.45) continue;
      const ww = (bw / n) * 0.34;
      lights.push([cx - bw / 2 + (bw / n) * (k + 0.5) - ww / 2, y - wallH * 0.68, ww, wallH * 0.36]);
    }
    y -= wallH;
    body += roof(cx, y + s * 0.14, tw, s * 0.62);
    y -= s * 0.36;
    tw *= 0.82;
  }
  body += box(cx - s * 0.035, y - s * 1.1, s * 0.07, s * 1.15) + circle(cx, y - s * 1.12, s * 0.07);
  for (let k = 1; k <= 5; k++) body += box(cx - s * 0.11, y - s * 0.18 * k, s * 0.22, s * 0.04);
  return { body, lights };
}

function torii(cx, base, w, h) {
  const pw = w * 0.075, d = [];
  for (const side of [-1, 1]) {
    const xb = cx + side * w * 0.35, xt = cx + side * w * 0.32;
    d.push(poly([[xb - pw / 2, base], [xt - pw * 0.4, base - h * 0.9], [xt + pw * 0.4, base - h * 0.9], [xb + pw / 2, base]]));
  }
  d.push(`M${f(cx - w * 0.6)},${f(base - h)}Q${f(cx)},${f(base - h * 0.89)} ${f(cx + w * 0.6)},${f(base - h)}` +
    `L${f(cx + w * 0.53)},${f(base - h * 0.92)}Q${f(cx)},${f(base - h * 0.82)} ${f(cx - w * 0.53)},${f(base - h * 0.92)}Z`);
  d.push(box(cx - w * 0.47, base - h * 0.88, w * 0.94, h * 0.05));
  d.push(box(cx - w * 0.45, base - h * 0.7, w * 0.9, h * 0.045));
  d.push(box(cx - w * 0.03, base - h * 0.85, w * 0.06, h * 0.16));
  return d.join("");
}

// A stone lantern (tōrō); returns the stone and the lit window [x, y, w, h].
function toro(cx, base, s) {
  let d = poly([[cx - s * 0.45, base], [cx - s * 0.36, base - s * 0.16], [cx + s * 0.36, base - s * 0.16], [cx + s * 0.45, base]]);
  d += box(cx - s * 0.13, base - s * 0.85, s * 0.26, s * 0.7);
  d += poly([[cx - s * 0.36, base - s * 0.85], [cx - s * 0.3, base - s * 0.97], [cx + s * 0.3, base - s * 0.97], [cx + s * 0.36, base - s * 0.85]]);
  d += box(cx - s * 0.26, base - s * 1.4, s * 0.06, s * 0.44) + box(cx + s * 0.2, base - s * 1.4, s * 0.06, s * 0.44);
  d += box(cx - s * 0.26, base - s * 1.43, s * 0.52, s * 0.05) + box(cx - s * 0.26, base - s * 1.0, s * 0.52, s * 0.04);
  d += roof(cx, base - s * 1.38, s * 1.2, s * 0.36);
  d += circle(cx, base - s * 1.8, s * 0.09);
  return { stone: d, window: [cx - s * 0.2, base - s * 1.36, s * 0.4, s * 0.36] };
}

// A figure seen from behind, standing still or walking; the cloak is drawn separately so it can
// carry the scene's accent colour.
function ronin(x, base, h, hat) {
  const u = h / 10, P = (pts) => poly(pts.map(([a, b]) => [x + a * u, base - b * u]));
  const cloak = P([[-1.3, 7.5], [-1.75, 4.5], [-2.2, 0.7], [-1.0, 0.5], [1.1, 0.5], [2.05, 0.8], [1.7, 4.5], [1.3, 7.5], [0, 7.95]]);
  let body = P([[-0.8, 0.7], [-0.75, 0], [-0.15, 0], [-0.15, 0.7]]) + P([[0.2, 0.7], [0.25, 0], [0.85, 0], [0.8, 0.7]]);
  body += circle(x, base - 8.5 * u, 0.72 * u);
  body += hat ? P([[-2.6, 8.5], [0, 10.15], [2.6, 8.5], [0, 8.85]]) : circle(x + 0.15 * u, base - 9.35 * u, 0.36 * u);
  body += P([[-2.7, 2.6], [2.3, 5.4], [2.36, 5.24], [-2.64, 2.44]]);
  body += P([[-2.1, 3.25], [1.6, 5.05], [1.66, 4.9], [-2.04, 3.1]]);
  return { cloak, body };
}

// A palm: curved, ringed trunk and drooping fronds. Without a trunk it is just a crown of fronds
// (for palms leaning in from outside the frame).
function palm(r, base, top, o) {
  const len = o.len ?? 440, n = o.fronds ?? 12, fan = o.fan ?? 2.5;
  let back = "", fore = "", ribs = "", trunk = "";
  if (base) {
    const c = [base[0] + (top[0] - base[0]) * 0.2 + (o.bow ?? 0), base[1] + (top[1] - base[1]) * 0.55];
    const pts = quad(base, c, top, 40);
    trunk = `<path d="${taper(pts, o.w0 ?? 54, o.w1 ?? 28)}" fill="${o.trunk}"/>`;
    let rings = "";
    for (let i = 1; i < pts.length - 1; i++) {
      const [px, py] = pts[i], [qx, qy] = pts[i + 1], d = Math.hypot(qx - px, qy - py) || 1;
      const w = lerp(o.w0 ?? 54, o.w1 ?? 28, i / (pts.length - 1)) / 2, nx = (-(qy - py) / d) * w, ny = ((qx - px) / d) * w;
      rings += `M${f(px - nx)},${f(py - ny)}Q${f(px + (qx - px) * 0.8)},${f(py + (qy - py) * 0.8 + 4)} ${f(px + nx)},${f(py + ny)}`;
    }
    trunk += `<path d="${rings}" fill="none" stroke="${o.rings}" stroke-width="2.5" opacity=".55"/>`;
    trunk += `<path d="${taper(pts.map(([px, py]) => [px + 9, py]), (o.w0 ?? 54) * 0.25, (o.w1 ?? 28) * 0.2)}" fill="${o.shine}" opacity=".35"/>`;
  }
  for (let k = 0; k < n; k++) {
    const ang = -Math.PI / 2 + (k / (n - 1) - 0.5) * 2 * fan + (r() - 0.5) * 0.25 + (o.tilt ?? 0);
    const dir = [Math.cos(ang), Math.sin(ang)], L = len * (0.72 + r() * 0.4) * (1 - Math.max(0, -dir[1]) * 0.4);
    const end = [top[0] + dir[0] * L, top[1] + dir[1] * L * 0.45 + L * 0.5];
    const ctrl = [top[0] + dir[0] * L * 0.6, top[1] + dir[1] * L * 0.6 - L * 0.12];
    const spine = quad(top, ctrl, end, o.seg ?? 30);
    let d = "";
    for (let i = 2; i < spine.length; i++) {
      const t = i / (spine.length - 1), [px, py] = spine[i], [qx, qy] = spine[i - 1];
      const ta = Math.atan2(py - qy, px - qx), ll = L * 0.2 * Math.sin(Math.PI * Math.min(1, t * 1.1)) + 10;
      for (const side of [-1, 1]) {
        const la = ta + side * (0.85 + r() * 0.25);
        d += leafPath(px, py, Math.atan2(Math.sin(la) + 0.8, Math.cos(la)), ll * (0.85 + r() * 0.3), ll * 0.085);
      }
    }
    if (k % 2) fore += d; else back += d;
    ribs += line(spine);
  }
  let nuts = "";
  if (base && o.nuts) for (let i = 0; i < 4; i++) nuts += circle(top[0] + (r() - 0.5) * 40, top[1] + 14 + r() * 22, 12 + r() * 4);
  return `<path d="${back}" fill="${o.dark}"/>${trunk}${nuts && `<path d="${nuts}" fill="${o.nuts}"/>`}` +
    `<path d="${fore}" fill="${o.leaf}"/><path d="${ribs}" fill="none" stroke="${o.rib}" stroke-width="3" opacity=".7"/>`;
}

// A heaped cumulus cloud: shaded underside, body, sunlit tops.
function cumulus(r, cx, base, w, h, tones) {
  const bumps = [], n = Math.round(w / 45);
  for (let i = 0; i < n; i++) {
    const u = r(), x = cx + (u - 0.5) * w;
    const prof = Math.pow(Math.max(0, 1 - Math.pow(2 * u - 1, 2)), 0.7);
    const rr = 34 + prof * h * (0.22 + r() * 0.22);
    bumps.push([x, Math.min(base - prof * h * (0.3 + r() * 0.55), base - rr * 0.5), rr]);
  }
  let s = oval(cx, base - 10, w * 0.47, 46), m = "", l = "";
  for (const [x, y, rr] of bumps) {
    s += circle(x + rr * 0.08, y + rr * 0.2, rr);
    m += circle(x, y, rr * 0.9);
    l += circle(x - rr * 0.2, y - rr * 0.24, rr * 0.6);
  }
  return `<path d="${s}" fill="${tones[0]}"/><path d="${m}" fill="${tones[1]}"/><path d="${l}" fill="${tones[2]}"/>`;
}

// Short horizontal glints on water, crowded toward a reflection column at fx.
function glints(r, n, x0, x1, y0, y1, fx = null, fw = 0) {
  let d = "";
  for (let i = 0; i < n; i++) {
    const y = y0 + Math.pow(r(), 1.3) * (y1 - y0), p = (y - y0) / (y1 - y0);
    const x = fx !== null && r() < 0.6 ? fx + (r() - 0.5) * fw * (0.5 + p) : lerp(x0, x1, r());
    d += box(x, y, (8 + r() * 40) * (0.4 + p * 1.4), 1.2 + p * 2.6);
  }
  return d;
}

// Static stars go in the layer itself, the twinkling ones in its motion overlay.
function stars(L, r, n, y0, y1, color) {
  let dim = "", bright = "", tw = "";
  for (let i = 0; i < n; i++) {
    const x = r() * W, y = y0 + Math.pow(r(), 1.5) * (y1 - y0), s = 0.6 + Math.pow(r(), 3) * 1.9;
    if (r() < 0.7) dim += circle(x, y, s); else bright += circle(x, y, s);
  }
  for (let i = 0; i < 14; i++) {
    const x = r() * W, y = y0 + r() * (y1 - y0) * 0.6;
    tw += `<g class="tw" style="animation-delay:-${(r() * 6).toFixed(1)}s"><circle cx="${f(x)}" cy="${f(y)}" r="2.3"/>` +
      `<path d="M${f(x - 10)},${f(y)}h20M${f(x)},${f(y - 10)}v20" stroke="${color}" stroke-width=".9" opacity=".6"/></g>`;
  }
  L.add(`<path d="${dim}" fill="${color}" opacity=".45"/><path d="${bright}" fill="${color}" opacity=".9"/>`);
  L.animate(".tw{animation:tw 5s ease-in-out infinite alternate}@keyframes tw{from{opacity:.2}to{opacity:1}}", `<g fill="${color}">${tw}</g>`);
}

// ---------- One layer file ----------

class Layer {
  constructor(name) {
    this.name = name;
    this.defs = [];
    this.parts = [];
    this.css = "";
    this.motion = [];
    this.motionCss = "";
    this.cache = new Map();
  }
  grad(kind, stops, attrs = "") {
    const key = kind + JSON.stringify(stops) + attrs;
    if (!this.cache.has(key)) {
      const id = "g" + this.cache.size;
      const s = stops.map(([o, c, a = 1]) => `<stop offset="${o}" stop-color="${c}"${a < 1 ? ` stop-opacity="${a}"` : ""}/>`).join("");
      this.defs.push(`<${kind}Gradient id="${id}" ${attrs}>${s}</${kind}Gradient>`);
      this.cache.set(key, `url(#${id})`);
    }
    return this.cache.get(key);
  }
  // Top-to-bottom gradient in canvas coordinates
  vert(stops, y0 = 0, y1 = H) {
    return this.grad("linear", stops, `x1="0" y1="${f(y0)}" x2="0" y2="${f(y1)}" gradientUnits="userSpaceOnUse"`);
  }
  horiz(stops, x0 = 0, x1 = W, extra = "") {
    return this.grad("linear", stops, `x1="${f(x0)}" y1="0" x2="${f(x1)}" y2="0" gradientUnits="userSpaceOnUse"${extra}`);
  }
  // Fades out from the middle of whatever it fills
  soft(color, a = 1, inner = 0) {
    return this.grad("radial", [[inner, color, a], [1, color, 0]]);
  }
  blur(sd) {
    const key = "blur" + sd;
    if (!this.cache.has(key)) {
      const id = "b" + this.cache.size;
      this.defs.push(`<filter id="${id}" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="${sd}"/></filter>`);
      this.cache.set(key, `url(#${id})`);
    }
    return this.cache.get(key);
  }
  add(...s) {
    this.parts.push(...s);
    return this;
  }
  // Animated details live in a small overlay file (<name>-fx.svg) drawn over the layer, so the big
  // layer itself never has to be redrawn per frame; phones and reduced-motion visitors skip it.
  animate(css, ...s) {
    if (!this.motionCss.includes(css)) this.motionCss += css;
    this.motion.push(...s);
    return this;
  }
  path(d, fill, extra = "") {
    return this.add(`<path d="${d}" fill="${fill}"${extra}/>`);
  }
  fill(fill) {
    return this.add(`<rect x="-40" y="-40" width="${W + 80}" height="${H + 80}" fill="${fill}"/>`);
  }
  // A soft glow or wisp of mist
  puff(cx, cy, rx, ry, color, a, inner = 0, rot = 0) {
    const t = rot ? ` transform="rotate(${rot} ${f(cx)} ${f(cy)})"` : "";
    return this.add(`<ellipse cx="${f(cx)}" cy="${f(cy)}" rx="${f(rx)}" ry="${f(ry)}" fill="${this.soft(color, a, inner)}"${t}/>`);
  }
  // A level bank of mist, thickest in the middle
  band(y0, y1, color, a) {
    return this.add(`<rect x="-40" y="${f(y0)}" width="${W + 80}" height="${f(y1 - y0)}" fill="${this.vert([[0, color, 0], [0.5, color, a], [1, color, 0]], y0, y1)}"/>`);
  }
  // Mist rising from below: clear at y0, full from y1 down
  rise(y0, y1, color, a) {
    const b = H + 40;
    return this.add(`<rect x="-40" y="${f(y0)}" width="${W + 80}" height="${f(b - y0)}" fill="${this.vert([[0, color, 0], [(y1 - y0) / (b - y0), color, a], [1, color, a]], y0, b)}"/>`);
  }
  // Lit windows or openings, each with a halo
  lights(list, core, glow, a = 0.3) {
    let d = "";
    for (const [x, y, w, h] of list) {
      d += box(x, y, w, h);
      this.puff(x + w / 2, y + h / 2, w * 2.6 + 10, h * 2 + 10, glow, a);
    }
    return this.path(d, core);
  }
  // A paper lantern hanging from a cord
  lantern(x, y, s, cord, tones) {
    this.puff(x, y, s * 4.5, s * 4.5, tones.glow, 0.32);
    this.add(`<path d="M${f(x)},${f(y - s - cord)}V${f(y - s)}" stroke="${tones.cap}" stroke-width="${f(Math.max(1.5, s * 0.05))}"/>`);
    this.add(`<ellipse cx="${f(x)}" cy="${f(y)}" rx="${f(s * 0.76)}" ry="${f(s)}" fill="${this.grad("radial", [[0, tones.core], [0.55, tones.light], [1, tones.edge]], 'cx=".5" cy=".45" r=".6"')}"/>`);
    let ribs = "";
    for (let k = -3; k <= 3; k++) {
      const dy = k * s * 0.24, hw = s * 0.76 * Math.sqrt(Math.max(0, 1 - (dy / s) ** 2));
      ribs += `M${f(x - hw)},${f(y + dy)}Q${f(x)},${f(y + dy + s * 0.06)} ${f(x + hw)},${f(y + dy)}`;
    }
    this.add(`<path d="${ribs}" fill="none" stroke="${tones.edge}" stroke-width="${f(Math.max(1, s * 0.03))}" opacity=".45"/>`);
    return this.path(box(x - s * 0.42, y - s * 1.08, s * 0.84, s * 0.16) + box(x - s * 0.42, y + s * 0.92, s * 0.84, s * 0.16), tones.cap);
  }
  save() {
    const doc = (css, body, defs = "") =>
      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" preserveAspectRatio="xMidYMax slice">` +
      `${MARK}<defs>${defs}</defs>${css ? `<style>${css}</style>` : ""}${body}</svg>\n`;
    write(`${this.name}.svg`, doc(this.css, this.parts.join(""), this.defs.join("")));
    if (this.motion.length) {
      write(`${this.name}-fx.svg`, doc(this.motionCss + "@media (prefers-reduced-motion:reduce){*{animation:none!important}}", this.motion.join("")));
    }
  }
}

// Writes a generated layer, unless your own art has taken its place.
function write(name, content) {
  const base = name.replace(/\.svg$/, ""), file = path.join(OUT, name);
  const own = RASTER.find((ext) => fs.existsSync(path.join(OUT, `${base}.${ext}`)));
  const handMade = fs.existsSync(file) && !fs.readFileSync(file, "utf8").includes(MARK);
  if (own || handMade) {
    if (own && fs.existsSync(file) && !handMade) fs.unlinkSync(file);
    console.log(name.padEnd(20), `kept your ${own ? `${base}.${own}` : "SVG"}`);
    return;
  }
  fs.writeFileSync(file, content);
  console.log(name.padEnd(20), (content.length / 1024).toFixed(1) + " KB");
}

// ======================= NIGHT: deep purple, moonlit, misty =======================

const PURPLE = ["#1c0732", "#3a1468", "#62289f", "#9a5ae6"]; // foliage: shadow, body, lit, petals
const LANTERN = { glow: "#b46cff", core: "#fff4ff", light: "#e3bcff", edge: "#8a3fd0", cap: "#0c0818" };

// 1 · A lone wanderer below a great moon, a purple tree leaning off a crag over still water.
function night1() {
  let r = rng(101);
  const sky = new Layer("night-1-sky");
  sky.fill(sky.vert([[0, "#06040d"], [0.35, "#120a24"], [0.62, "#261742"], [0.82, "#43316a"], [1, "#5a4785"]]));
  stars(sky, r, 300, 0, 950, "#ece4ff");
  sky.puff(260, 120, 1150, 360, "#07040e", 0.85).puff(2520, 40, 820, 240, "#07040e", 0.7);
  sky.puff(1990, 470, 900, 820, "#9f7cf0", 0.24).puff(1990, 470, 470, 470, "#ece2ff", 0.4);
  sky.add(`<circle cx="1990" cy="470" r="250" fill="${sky.grad("radial", [[0, "#fefcff"], [0.75, "#efe7ff"], [1, "#cdbcf3"]], 'cx=".42" cy=".4" r=".62"')}"/>`);
  r = rng(7);
  let maria = "";
  for (let i = 0; i < 9; i++) {
    const a = r() * 6.28, d = Math.sqrt(r()) * 170;
    maria += oval(1990 + Math.cos(a) * d, 470 + Math.sin(a) * d, 26 + r() * 54, 18 + r() * 34, r() * 3);
  }
  sky.path(maria, "#b9a8e4", ` opacity=".16"`);
  // Cloud streaks drifting across the moon
  sky.puff(1850, 612, 600, 54, "#170f2c", 0.9).puff(2230, 668, 480, 40, "#170f2c", 0.85).puff(1600, 700, 520, 34, "#170f2c", 0.6);
  sky.puff(1910, 594, 430, 14, "#d6c6fb", 0.35).puff(2260, 652, 300, 10, "#d6c6fb", 0.3);
  sky.puff(1280, 900, 1500, 160, "#7a65b4", 0.3);
  sky.save();

  r = rng(202);
  const far = new Layer("night-1-far");
  const back = displace(r, [[-120, 1000], [260, 900], [600, 960], [1000, 950], [1400, 990], [1760, 950], [2120, 860], [2420, 905], [2700, 870]], 0.12, 6);
  far.path(area(back), "#3a2b61");
  const deadX = 2350, dead = growTree(r, deadX, yAt(back, deadX) + 4, -1.7, 64, 9, 5, { spread: 0.55, shrink: 0.66 });
  far.path(dead.wood, "#32255a");
  far.band(860, 1060, "#a593d6", 0.45);
  far.path(area(wave(r, 1012, [[18, 700], [8, 230], [3, 80]])), "#2a1f4c");
  far.add(`<rect x="-40" y="1036" width="${W + 80}" height="${H - 1000}" fill="${far.vert([[0, "#3f3068"], [0.3, "#1f1638"], [1, "#0c0817"]], 1036, H)}"/>`);
  far.puff(1990, 1080, 330, 46, "#cdb9ff", 0.45);
  far.path(glints(r, 170, 0, W, 1046, H, 1990, 260), "#e8ddff", ` opacity=".55"`);
  far.band(1000, 1110, "#8f7cc6", 0.5);
  far.save();

  r = rng(303);
  const mid = new Layer("night-1-mid");
  const tree = growTree(r, 330, 905, -1.42, 170, 58, 6, { spread: 0.55, shrink: 0.7, lean: [-0.2, -1, 0.12] });
  mid.path(tree.wood, "#140c22");
  mid.add(canopy(r, tree.tips, 56, PURPLE, { light: [0.75, -0.65], specks: 2 }));
  const crag = rock(r, [[-140, 930], [90, 880], [330, 890], [520, 915], [620, 965], [590, 1040], [660, 1110], [560, 1200], [600, 1300], [520, 1480], [-140, 1480]], 0.14, 5);
  mid.path(poly(crag), mid.vert([[0, "#261a42"], [1, "#0b0716"]], 880, H));
  mid.add(`<path d="${line(crag.slice(0, Math.floor(crag.length * 0.42)))}" fill="none" stroke="#a48ee6" stroke-width="3" opacity=".35"/>`);
  mid.path(grass(r, 18, 40, 560, 905, 34), "#140c22");
  mid.band(1150, 1330, "#5d4a92", 0.5);
  mid.save();

  r = rng(404);
  const near = new Layer("night-1-near");
  const pillar = rock(r, [[2010, 1480], [2050, 1300], [2090, 1170], [2150, 1104], [2240, 1088], [2330, 1094], [2392, 1150], [2424, 1260], [2480, 1480]], 0.1, 5);
  near.puff(2240, 1010, 220, 160, "#a78bfa", 0.25);
  near.path(poly(pillar), near.vert([[0, "#21173b"], [1, "#0a0613"]], 1088, H));
  near.add(`<path d="${line(pillar.slice(0, Math.floor(pillar.length * 0.5)))}" fill="none" stroke="#b39cf0" stroke-width="3" opacity=".45"/>`);
  const man = ronin(2246, 1094, 150, false);
  near.path(man.cloak, near.vert([[0, "#7c3aed"], [1, "#3b0f74"]], 940, 1094)).path(man.body, "#0a0612");
  const ledge = rock(r, [[-140, 1250], [60, 1222], [250, 1236], [420, 1290], [520, 1370], [580, 1480], [-140, 1480]], 0.16, 5);
  const shrub = growTree(r, 170, 1236, -1.15, 64, 16, 5, { spread: 0.6, shrink: 0.68 });
  near.path(shrub.wood, "#0e0819");
  near.add(canopy(r, shrub.tips, 28, PURPLE, { light: [0.8, -0.6], specks: 2 }));
  near.path(poly(ledge), near.vert([[0, "#1b1231"], [1, "#09060f"]], 1220, H));
  let ripples = "";
  for (let i = 0; i < 26; i++) ripples += oval(lerp(600, 2000, r()), 1250 + r() * 170, 40 + r() * 120, 3 + r() * 3);
  near.path(ripples, "#cdbcfb", ` opacity=".12"`);
  near.band(1240, 1400, "#4a3a78", 0.55);
  near.save();

  r = rng(505);
  const front = new Layer("night-1-front");
  const bough = growTree(r, 2660, -60, 2.55, 150, 30, 5, { spread: 0.5, shrink: 0.7 });
  front.path(bough.wood, "#0a0612");
  front.add(canopy(r, bough.tips, 34, ["#0d0518", "#1d0a36", "#341460", "#7a45c6"], { light: [-0.7, 0.7], specks: 2 }));
  const lc = rock(r, [[-140, 1380], [90, 1350], [250, 1372], [380, 1420], [430, 1480], [-140, 1480]], 0.2, 4);
  const rc = rock(r, [[2180, 1480], [2260, 1400], [2420, 1360], [2700, 1350], [2700, 1480]], 0.2, 4);
  front.path(poly(lc) + poly(rc), "#07040d");
  front.path(grass(r, 12, -20, 330, 1400, 70) + grass(r, 12, 2260, 2580, 1390, 80), "#07040d");
  let petals = "";
  for (let i = 0; i < 56; i++) {
    const x = r() < 0.6 ? r() * 900 : 1700 + r() * 860, y = r() * 1300;
    petals += oval(x, y, 5 + r() * 5, 2.5 + r() * 2, r() * 3);
  }
  front.path(petals, "#a670f2", ` opacity=".8"`);
  front.puff(400, 1440, 1000, 110, "#2c2048", 0.7).puff(2200, 1440, 900, 100, "#2c2048", 0.7);
  front.save();
}

// 2 · A temple town in the mountains: lantern-lit street climbing into the mist.
function night2() {
  let r = rng(111);
  const sky = new Layer("night-2-sky");
  sky.fill(sky.vert([[0, "#0a0716"], [0.3, "#271d49"], [0.58, "#655799"], [0.78, "#a497d4"], [1, "#c6bcec"]]));
  stars(sky, r, 140, 0, 420, "#efe8ff");
  sky.puff(1280, 560, 900, 560, "#f1eaff", 0.5);
  sky.puff(600, 330, 900, 120, "#3b2e68", 0.55).puff(2050, 280, 800, 110, "#3b2e68", 0.5);
  sky.puff(1000, 470, 700, 70, "#e4dafc", 0.4).puff(1700, 520, 640, 60, "#e4dafc", 0.35);
  sky.save();

  r = rng(222);
  const far = new Layer("night-2-far");
  const spire = (cx, base, w, h) => poly(rock(r, [[cx - w / 2, base], [cx - w * 0.22, base - h * 0.55], [cx - w * 0.06, base - h], [cx + w * 0.07, base - h * 0.96], [cx + w * 0.24, base - h * 0.5], [cx + w / 2, base]], 0.12, 6));
  far.path(spire(1280, 1040, 1000, 600) + spire(1000, 1040, 560, 470) + spire(1580, 1040, 600, 520), "#8a7eb8");
  far.band(560, 860, "#ddd3f6", 0.45);
  const temple = pagoda(r, 1280, 960, 330, 4, 64);
  far.path(temple.body, "#5d5089");
  far.lights(temple.lights, "#f3e4ff", "#c084fc", 0.25);
  far.path(spire(200, 1140, 760, 1080) + spire(2380, 1140, 800, 1140), "#5d508f");
  far.path(spire(560, 1140, 420, 760) + spire(2030, 1140, 460, 820), "#695c9c");
  let birds = "";
  for (let i = 0; i < 16; i++) {
    const x = 1440 + r() * 380, y = 360 + r() * 200, s = 5 + r() * 5;
    birds += `M${f(x - s)},${f(y - s * 0.4)}Q${f(x - s * 0.4)},${f(y - s * 0.5)} ${f(x)},${f(y)}Q${f(x + s * 0.4)},${f(y - s * 0.5)} ${f(x + s)},${f(y - s * 0.4)}`;
  }
  far.add(`<path d="${birds}" fill="none" stroke="#f4efff" stroke-width="1.6" opacity=".75"/>`);
  far.band(880, 1100, "#c3b7ea", 0.6);
  far.save();

  r = rng(333);
  const mid = new Layer("night-2-mid");
  const lcliff = rock(r, [[-140, 1480], [-140, 560], [60, 520], [210, 540], [330, 600], [410, 700], [440, 820], [500, 930], [540, 1060], [600, 1220], [620, 1480]], 0.1, 5);
  const rcliff = rock(r, [[2700, 1480], [2700, 500], [2480, 460], [2300, 480], [2180, 560], [2120, 690], [2080, 820], [2030, 960], [1990, 1120], [1970, 1480]], 0.1, 5);
  const lp = pagoda(r, 220, 545, 320, 4, 70), rp = pagoda(r, 2370, 488, 360, 5, 70);
  mid.path(lp.body + rp.body, "#1d1535");
  mid.lights(lp.lights.concat(rp.lights), "#f3dcff", "#b46cff", 0.35);
  mid.path(poly(lcliff) + poly(rcliff), mid.vert([[0, "#33285a"], [1, "#171129"]], 460, 1300));
  for (const [x, y, a] of [[400, 690, -0.35], [2140, 640, -2.8]]) {
    const p = growTree(r, x, y, a, 70, 14, 4, { spread: 0.6, flat: 0.5, shrink: 0.68 });
    mid.path(p.wood, "#130d24");
    mid.add(canopy(r, p.tips, 34, ["#120c22", "#1d1538", "#2c2252", "#2c2252"], { squash: 0.45, light: [0, -1] }));
  }
  mid.rise(940, 1180, "#8a7cbc", 0.62);
  mid.save();

  r = rng(444);
  const near = new Layer("night-2-near");
  const road = poly([[1200, 1010], [1360, 1010], [1880, 1480], [680, 1480]]);
  near.path(road, near.vert([[0, "#6a5c98"], [0.4, "#3a3060"], [1, "#1c1630"]], 1010, H));
  let joints = "";
  for (let k = 1; k < 16; k++) {
    const t = Math.pow(k / 16, 1.6), y = lerp(1010, H, t), hw = lerp(80, 600, t);
    joints += `M${f(1280 - hw)},${f(y)}L${f(1280 + hw)},${f(y)}`;
    for (let j = 0; j < 4; j++) {
      const x = 1280 + (r() - 0.5) * 2 * hw;
      joints += `M${f(x)},${f(y)}L${f(x + (x - 1280) * 0.08)},${f(y + 10 + t * 60)}`;
    }
  }
  near.add(`<path d="${joints}" fill="none" stroke="#1a1430" stroke-width="2.5" opacity=".55"/>`);
  near.puff(1000, 1360, 220, 50, "#c084fc", 0.3).puff(1600, 1330, 220, 46, "#c084fc", 0.3);
  near.band(980, 1120, "#a597d4", 0.6);
  // Left row of houses with banners and lanterns
  near.path(poly([[-140, 690], [530, 775], [600, 745], [586, 806], [-140, 772]]) + poly([[-140, 772], [440, 812], [450, 1480], [-140, 1480]]), "#140f25");
  near.path(box(110, 900, 230, 150), "#e7c9ff", ` opacity=".55"`);
  near.puff(225, 975, 260, 160, "#b46cff", 0.25);
  near.add(`<path d="M110,950h230M110,1000h230M168,900v150M225,900v150M282,900v150" stroke="#140f25" stroke-width="5"/>`);
  near.path(box(470, 820, 8, 660) + box(540, 840, 8, 640), "#0e0a1a");
  near.path(box(478, 850, 56, 300), "#3d1470");
  near.add(`<circle cx="506" cy="920" r="18" fill="none" stroke="#c8a6f7" stroke-width="3" opacity=".7"/>`);
  for (const [x, y] of [[90, 840], [250, 858], [400, 876]]) near.lantern(x, y, 34, 40, LANTERN);
  // Right row
  near.path(poly([[2700, 640], [2040, 735], [1970, 705], [1984, 768], [2700, 712]]) + poly([[2700, 712], [2130, 772], [2120, 1480], [2700, 1480]]), "#140f25");
  near.path(box(2240, 860, 260, 170), "#e7c9ff", ` opacity=".5"`);
  near.puff(2370, 945, 280, 170, "#b46cff", 0.25);
  near.add(`<path d="M2240,917h260M2240,973h260M2305,860v170M2370,860v170M2435,860v170" stroke="#140f25" stroke-width="5"/>`);
  near.path(box(2060, 790, 70, 330), "#e9d5ff", ` opacity=".85"`);
  near.path(box(2060, 790, 70, 18) + box(2060, 1104, 70, 16), "#140f25");
  near.add(`<circle cx="2095" cy="890" r="22" fill="none" stroke="#5b21b6" stroke-width="5"/><path d="M2078,950q17,-6 34,0M2082,985q13,-5 26,0M2080,1020q15,-6 30,0" fill="none" stroke="#5b21b6" stroke-width="6" stroke-linecap="round"/>`);
  for (const [x, y] of [[2190, 800], [2330, 790], [2480, 776]]) near.lantern(x, y, 36, 40, LANTERN);
  near.save();

  r = rng(555);
  const front = new Layer("night-2-front");
  for (const [x, y, a] of [[-60, 120, -0.08], [2620, 60, -3.06]]) {
    const p = growTree(r, x, y, a, 200, 46, 5, { spread: 0.5, flat: 0.55, shrink: 0.68 });
    front.path(p.wood, "#0a0714");
    front.add(canopy(r, p.tips, 50, ["#08060f", "#110c1f", "#1d1533", "#1d1533"], { squash: 0.42, light: [0, -1] }));
  }
  front.lantern(2330, 330, 74, 260, LANTERN);
  const walker = ronin(1050, 1420, 250, true);
  front.puff(1050, 1300, 200, 170, "#c084fc", 0.18);
  front.path(walker.cloak, front.vert([[0, "#6d28d9"], [1, "#2e0f5e"]], 1170, 1420)).path(walker.body, "#09060f");
  front.puff(500, 1440, 1000, 100, "#1c1530", 0.75).puff(2100, 1440, 1000, 100, "#1c1530", 0.75);
  front.save();
}

// 3 · A torii standing in a still lake below the snowy peak; bamboo and maple at the edges.
function night3() {
  let r = rng(121);
  const sky = new Layer("night-3-sky");
  const skyFill = sky.vert([[0, "#05030c"], [0.45, "#170f2e"], [0.72, "#33235a"], [1, "#54408a"]]);
  sky.fill(skyFill);
  sky.puff(1100, 420, 1500, 150, "#8b6fd6", 0.22, 0, -14).puff(1100, 420, 900, 60, "#d9c9ff", 0.18, 0, -14);
  let band = "";
  for (let i = 0; i < 380; i++) {
    const t = r(), x = lerp(-200, 2500, t), y = 420 + (x - 1100) * Math.tan((-14 * Math.PI) / 180) + (r() - 0.5) * 200 * (0.4 + r());
    band += circle(x, y, 0.5 + r() * 1.1);
  }
  sky.path(band, "#efe7ff", ` opacity=".6"`);
  stars(sky, r, 300, 0, 900, "#efe7ff");
  sky.puff(2090, 250, 260, 260, "#c9b3ff", 0.3);
  sky.defs.push(`<mask id="crescent"><circle cx="2090" cy="250" r="62" fill="#fff"/><circle cx="2118" cy="232" r="56" fill="#000"/></mask>`);
  sky.add(`<circle cx="2090" cy="250" r="62" fill="#f6f0ff" mask="url(#crescent)"/>`);
  sky.save();

  r = rng(232);
  const far = new Layer("night-3-far");
  const peak = rock(r, [[980, 1040], [1300, 860], [1480, 720], [1600, 636], [1660, 630], [1730, 668], [1900, 780], [2200, 920], [2500, 1040]], 0.05, 6);
  const capLine = peak.filter(([, y]) => y < 760);
  const cap = capLine.concat(displace(r, [[capLine.at(-1)[0], capLine.at(-1)[1]], [1660, 740], [capLine[0][0], capLine[0][1]]], 0.25, 4)
    .map(([x, y], i) => [x, y + (i % 4 === 1 ? 26 : 0)]));
  const mountains = `<path d="${area(peak, 1040)}" fill="#54447f"/><path d="${poly(cap)}" fill="#ddd0f7" opacity=".75"/>`;
  const ridgeL = area(rock(r, [[-120, 930], [200, 870], [520, 920], [900, 980], [1200, 1040]], 0.1, 6), 1040);
  const ridgeR = area(rock(r, [[1900, 1040], [2200, 960], [2450, 900], [2700, 930]], 0.1, 6), 1040);
  far.add(mountains).path(ridgeL + ridgeR, "#3f3271");
  far.band(900, 1060, "#a796da", 0.45);
  far.add(`<rect x="-40" y="1036" width="${W + 80}" height="${H - 1000}" fill="${far.vert([[0, "#4b3c7c"], [0.3, "#271d4b"], [1, "#100b20"]], 1036, H)}"/>`);
  far.add(`<g transform="translate(0 2076) scale(1 -1)" opacity=".28">${mountains}<path d="${ridgeL + ridgeR}" fill="#3f3271"/></g>`);
  far.path(glints(r, 140, 0, W, 1050, H), "#d8caff", ` opacity=".35"`);
  far.band(1010, 1100, "#9e8cd2", 0.5);
  far.save();

  r = rng(343);
  const mid = new Layer("night-3-mid");
  const isle = poly(rock(r, [[150, 1092], [240, 1050], [420, 1028], [570, 1040], [720, 1092]], 0.12, 5));
  const shrine = pagoda(r, 420, 1034, 150, 3, 34);
  const isleArt = `<path d="${isle + shrine.body}" fill="#1b1331"/>`;
  const pine = growTree(r, 590, 1040, -1.2, 60, 10, 4, { spread: 0.6, flat: 0.5, shrink: 0.68 });
  mid.add(`<g transform="translate(0 2184) scale(1 -1)" opacity=".3">${isleArt}</g>`, isleArt);
  mid.path(pine.wood, "#1b1331");
  mid.add(canopy(r, pine.tips, 22, ["#150f28", "#1f1739", "#2c2250", "#2c2250"], { squash: 0.45 }));
  mid.lights(shrine.lights, "#f3dcff", "#b46cff", 0.35);
  const gate = torii(2080, 1180, 440, 500);
  mid.add(`<g transform="translate(0 2360) scale(1 -1)" opacity=".32"><path d="${gate}" fill="#4c1d95"/></g>`);
  mid.puff(2080, 900, 380, 320, "#a855f7", 0.16);
  mid.path(gate, mid.vert([[0, "#5b21b6"], [1, "#2a0d55"]], 680, 1180));
  mid.band(1110, 1250, "#8d7cc6", 0.5);
  mid.save();

  r = rng(454);
  const near = new Layer("night-3-near");
  let stalks = "", nodes = "", leaves = "";
  for (let i = 0; i < 10; i++) {
    const x = -30 + i * 46 + r() * 30, w = 16 + r() * 18, lean = (r() - 0.25) * 90;
    const pts = quad([x, 1480], [x + lean * 0.2, 700], [x + lean, -80], 30);
    stalks += taper(pts, w, w * 0.7);
    for (let k = 3; k < pts.length - 1; k += 3) nodes += box(pts[k][0] - w * 0.45, pts[k][1], w * 0.9, 3);
    for (let k = 0; k < 4 + r() * 3; k++) {
      const [px, py] = pts[Math.floor(2 + r() * 20)];
      for (let j = 0; j < 5; j++) leaves += leafPath(px, py, (r() < 0.65 ? 0.3 : 2.7) + (r() - 0.5) * 0.9, 60 + r() * 50, 7 + r() * 3);
    }
  }
  near.path(stalks, near.horiz([[0, "#120c22"], [1, "#24193f"]], 0, 520)).path(nodes, "#3a2d60", ` opacity=".8"`).path(leaves, "#1b1330");
  const mapleTree = growTree(r, 2600, 1340, -2.05, 170, 52, 6, { spread: 0.5, shrink: 0.7, up: 0.08 });
  near.path(mapleTree.wood, "#100a1c");
  near.add(canopy(r, mapleTree.tips, 46, PURPLE, { light: [-0.7, -0.7], specks: 2, shape: maple }));
  near.path(area(wave(r, 1330, [[14, 600], [6, 140]])), "#0d0918").path(grass(r, 40, -40, 2600, 1336, 46), "#0d0918");
  near.rise(1240, 1400, "#3a2c62", 0.5);
  near.save();

  r = rng(565);
  const front = new Layer("night-3-front");
  const lamp = toro(330, 1450, 300);
  front.puff(330, 1000, 240, 200, "#c084fc", 0.35);
  front.path(lamp.stone, front.vert([[0, "#2a2140"], [1, "#0b0815"]], 870, 1450));
  front.lights([lamp.window], "#f6e6ff", "#b46cff", 0.45);
  const [wx, wy, ww, wh] = lamp.window;
  front.add(`<path d="M${f(wx + ww / 2)},${f(wy)}v${f(wh)}M${f(wx)},${f(wy + wh / 2)}h${f(ww)}" stroke="#1a1428" stroke-width="7"/>`);
  let reeds = "";
  for (let i = 0; i < 22; i++) {
    const x = 2200 + r() * 380, h = 160 + r() * 200, bend = (r() - 0.6) * 60;
    reeds += blade(x, 1460, h, 3, bend);
    if (r() < 0.4) reeds += oval(x + bend * 0.85, 1460 - h * 0.85, 6, 22, Math.atan2(h, bend) - Math.PI / 2);
  }
  front.path(reeds, "#08050f");
  let fall = "";
  for (let i = 0; i < 40; i++) fall += oval(r() < 0.55 ? 1700 + r() * 860 : r() * 900, r() * 1300, 5 + r() * 5, 2.5 + r() * 2, r() * 3);
  front.path(fall, "#9a5ae6", ` opacity=".8"`);
  let spray = "";
  for (let i = 0; i < 40; i++) spray += leafPath(-20 + r() * 380, -20 + r() * 60, 0.6 + r() * 1.2, 70 + r() * 70, 8 + r() * 4);
  front.path(spray, "#0a0714");
  front.puff(1300, 1450, 1500, 100, "#1c1530", 0.7);
  front.save();
}

// ======================= DAY: a bright, quiet office in the tropics =======================
// Warm whites, linen, light oak and sage under a pale sky; soft bloom, haze and light shafts
// in place of outlines. The three scenes walk you in: terrace, gallery, study.

const DAY_SKY = [[0, "#c6dbe4"], [0.42, "#dce8ec"], [0.78, "#efeee7"], [1, "#f6f0e4"]];
const SLIM_PALM = { trunk: "#b9a78e", rings: "#8d7c66", shine: "#f3e9d8", dark: "#6a8f63", leaf: "#8fb27c", rib: "#77955f", nuts: null, len: 270, fronds: 11, w0: 22, w1: 12, seg: 18 };
const HAZE_JUNGLE = ["#a9bfb6", "#b6cac1", "#c6d6cd", "#c6d6cd"];
const NEAR_JUNGLE = ["#7a9a7d", "#8aa98a", "#a3be9c", "#a3be9c"];
const WALL = [[0, "#ece5da"], [0.5, "#f8f4ee"], [1, "#ebe3d7"]];
const OAK = [[0, "#e4cba6"], [1, "#cfae84"]];

// Pale sky with a sun bloom, soft clouds, high wisps and light shafts fanning away from the sun.
function softSky(L, r, o) {
  const [sx, sy] = o.sun;
  L.fill(L.vert(DAY_SKY));
  L.puff(sx, sy, 1200, 980, "#fff8ea", 0.7).puff(sx, sy, 300, 300, "#ffffff", 0.95, 0.25);
  const tones = ["#d3dce1", L.grad("linear", [[0, "#ffffff"], [0.6, "#f7f7f5"], [1, "#e1e7e9"]], 'x1="0" y1="0" x2="0" y2="1"'), "#ffffff"];
  L.add(`<g filter="${L.blur(6)}" opacity=".92">${o.clouds.map(([x, b, w, h]) => cumulus(r, x, b, w, h, tones)).join("")}</g>`);
  for (const [x, y, rx, rot] of o.wisps) L.puff(x, y, rx, rx * 0.06, "#ffffff", 0.65, 0, rot);
  let rays = "";
  for (let i = 0; i < 7; i++) {
    const a = lerp(o.rays[0], o.rays[1], i / 6) + (r() - 0.5) * 0.06, s = 0.025 + r() * 0.03;
    rays += poly([[sx, sy], [sx + Math.cos(a - s) * 3200, sy + Math.sin(a - s) * 3200], [sx + Math.cos(a + s) * 3200, sy + Math.sin(a + s) * 3200]]);
  }
  L.add(`<g filter="${L.blur(16)}" opacity=".28"><path d="${rays}" fill="#ffffff"/></g>`);
}

// A soft ridge whose top edge is broken up by tree crowns.
function jungleRidge(L, r, keys, tones, size, rough = 0.1) {
  const edge = rock(r, keys, rough, 6);
  L.path(area(edge), tones[1]);
  const tips = [];
  for (let i = 0; i < edge.length; i += 5) if (edge[i][0] > -100 && edge[i][0] < W + 100) tips.push([edge[i][0], edge[i][1] + size * 0.3]);
  L.add(canopy(r, tips, size, tones, { light: [0.3, -0.95] }));
  return edge;
}

// A waterfall: a pale sheet, strands that stream down (CSS), and mist where it lands.
function waterfall(L, r, x, top, bottom, w) {
  L.add(`<path d="M${f(x - w / 2)},${f(top)}C${f(x - w * 0.55)},${f(top + 60)} ${f(x - w * 0.6)},${f(bottom - 200)} ${f(x - w * 0.75)},${f(bottom)}` +
    `L${f(x + w * 0.75)},${f(bottom)}C${f(x + w * 0.6)},${f(bottom - 200)} ${f(x + w * 0.55)},${f(top + 60)} ${f(x + w / 2)},${f(top)}Z" ` +
    `fill="${L.vert([[0, "#ffffff", 0.7], [0.5, "#eef5f4", 0.8], [1, "#ffffff", 0.95]], top, bottom)}"/>`);
  let s = "";
  for (let i = 0; i < Math.round(w / 4); i++) {
    const sx = x + (r() - 0.5) * w * 0.95, dash = 50 + r() * 90;
    s += `<path class="fall" style="animation-duration:${(1 + r() * 1.4).toFixed(2)}s" d="M${f(sx)},${f(top)}Q${f(sx + (sx - x) * 0.1)},${f((top + bottom) / 2)} ${f(sx + (sx - x) * 0.5)},${f(bottom)}" ` +
      `stroke="${r() < 0.55 ? "#ffffff" : "#cfe0df"}" stroke-width="${f(1.2 + r() * 3.5)}" stroke-dasharray="${f(dash)} ${f(180 - dash)}" stroke-dashoffset="${f(r() * 180)}" opacity="${(0.4 + r() * 0.5).toFixed(2)}"/>`;
  }
  L.animate(".fall{animation:fall linear infinite}@keyframes fall{to{stroke-dashoffset:-180}}", `<g fill="none">${s}</g>`);
  L.puff(x, top + 6, w * 0.9, 14, "#ffffff", 0.8);
  for (let i = 0; i < 6; i++) L.puff(x + (r() - 0.5) * w * 2.2, bottom - r() * 50, w * (1 + r()), 40 + r() * 40, "#ffffff", 0.75);
}

// Aloe vera: a rosette of thick, tapering grey-green leaves, outer ones arching out.
function aloe(r, cx, base, s) {
  let back = "", fore = "", lit = "", teeth = "";
  const n = 13;
  for (let i = 0; i < n; i++) {
    const t = i / (n - 1), off = t - 0.5;
    const a = -Math.PI / 2 + off * 2.4 + (r() - 0.5) * 0.12, len = s * (0.7 + r() * 0.3) * (1 - Math.abs(off) * 0.45);
    const x = cx + off * s * 0.16, bow = off * s * 0.5, w = s * 0.085;
    const leaf = leafPath(x, base, a, len, w, bow);
    if (Math.abs(off) > 0.22) back += leaf; else fore += leaf;
    lit += leafPath(x + Math.cos(a + 1.57) * w * 0.3, base, a, len * 0.85, w * 0.3, bow);
    for (let k = 2; k < 8; k++) {
      const p = quad([x, base], [x + Math.cos(a) * len / 2 - Math.sin(a) * bow, base + Math.sin(a) * len / 2 + Math.cos(a) * bow], [x + Math.cos(a) * len, base + Math.sin(a) * len], 10)[k];
      teeth += circle(p[0] + Math.cos(a + 1.57) * w * 0.9, p[1] + Math.sin(a + 1.57) * w * 0.9, 1.6);
    }
  }
  return `<path d="${back}" fill="#7f9f86"/><path d="${fore}" fill="#93b39a"/><path d="${lit}" fill="#c3d8c4" opacity=".55"/><path d="${teeth}" fill="#eef3e8" opacity=".8"/>`;
}

// Sea buckthorn: slender grey stems, narrow silvery leaves and clusters of orange berries.
function buckthorn(r, x, base, h, n = 6) {
  let wood = "", leaves = "", leavesLit = "", berries = "", shine = "";
  for (let i = 0; i < n; i++) {
    const a = -Math.PI / 2 + (i / (n - 1) - 0.5) * 0.9 + (r() - 0.5) * 0.2, len = h * (0.7 + r() * 0.35);
    const end = [x + Math.cos(a) * len, base + Math.sin(a) * len];
    const pts = quad([x + (r() - 0.5) * 10, base], [x + Math.cos(a) * len * 0.5 + (r() - 0.5) * 60, base + Math.sin(a) * len * 0.5], end, 20);
    wood += taper(pts, 6, 1.5);
    for (let k = 4; k < pts.length; k++) {
      const [px, py] = pts[k], [qx, qy] = pts[k - 1], ta = Math.atan2(py - qy, px - qx), t = k / pts.length;
      for (const side of [-1, 1]) {
        if (r() < 0.25) continue;
        const la = ta + side * (0.45 + r() * 0.35);
        const leaf = leafPath(px, py, la, 26 + r() * 22, 2.6);
        if (r() < 0.5) leaves += leaf; else leavesLit += leaf;
      }
      if (t > 0.3 && t < 0.85 && r() < 0.7) {
        for (let b = 0; b < 4; b++) {
          const bx = px + (r() - 0.5) * 12, by = py + (r() - 0.5) * 12, br = 4 + r() * 2.5;
          berries += circle(bx, by, br);
          shine += circle(bx - br * 0.35, by - br * 0.35, br * 0.3);
        }
      }
    }
  }
  return `<path d="${wood}" fill="#8a7d70"/><path d="${leaves}" fill="#93a48c"/><path d="${leavesLit}" fill="#bccab3"/>` +
    `<path d="${berries}" fill="#ee9634"/><path d="${shine}" fill="#ffe0a8" opacity=".8"/>`;
}

// A plain ceramic planter with a soft contact shadow.
function pot(L, cx, base, w, h, tone = ["#e3ddd3", "#ffffff", "#d6cec2"]) {
  L.puff(cx, base + 2, w * 0.75, 16, "#7d6f5f", 0.35);
  L.path(`M${f(cx - w / 2)},${f(base - h)}H${f(cx + w / 2)}L${f(cx + w * 0.44)},${f(base - 8)}Q${f(cx + w * 0.42)},${f(base)} ${f(cx + w * 0.34)},${f(base)}` +
    `H${f(cx - w * 0.34)}Q${f(cx - w * 0.42)},${f(base)} ${f(cx - w * 0.44)},${f(base - 8)}Z`, L.horiz([[0, tone[0]], [0.35, tone[1]], [1, tone[2]]], cx - w / 2, cx + w / 2));
  return L.path(oval(cx, base - h, w / 2, 7), "#8c7a66");
}

// Floor boards or tiles running toward a vanishing point.
function floorLines(y0, y1, vx, vy, step, rows = []) {
  let d = "";
  for (let x1 = -3000; x1 <= W + 3000; x1 += step) d += `M${f(vx + (x1 - vx) * ((y0 - vy) / (y1 - vy)))},${f(y0)}L${f(x1)},${f(y1)}`;
  for (const y of rows) d += `M-40,${f(y)}H${W + 40}`;
  return d;
}

// Shafts of sunlight slanting into a room.
function shafts(L, list, a = 0.18) {
  L.add(`<g filter="${L.blur(14)}" opacity="${a}"><path d="${list.map(poly).join("")}" fill="#fff6e2"/></g>`);
}

// 1 · The terrace: an office's white terrace above a misty jungle valley, a waterfall in the cliff.
function day1() {
  let r = rng(611);
  const sky = new Layer("day-1-sky");
  softSky(sky, r, { sun: [2180, 160], rays: [1.95, 2.75], clouds: [[620, 840, 1300, 380], [1680, 900, 640, 200], [2400, 880, 420, 150]], wisps: [[420, 230, 520, -4], [1100, 170, 420, -3], [1800, 360, 380, 3]] });
  sky.save();

  r = rng(622);
  const far = new Layer("day-1-far");
  jungleRidge(far, r, [[-140, 1000], [160, 830], [480, 780], [820, 870], [1150, 960], [1500, 1000]], HAZE_JUNGLE, 30);
  // The lake fills the whole valley floor, so its shores are the hills themselves, never a straight cut
  far.path(box(-40, 972, W + 80, H - 932), far.vert([[0, "#d6ebe6"], [0.25, "#c4e1da"], [1, "#b2d6cf"]], 972, H));
  far.path(glints(r, 110, 0, W, 980, 1180), "#ffffff", ` opacity=".5"`);
  far.band(860, 1010, "#f6f3ec", 0.55);
  const cliff = rock(r, [[1520, H + 40], [1600, 1060], [1780, 760], [1880, 480], [1980, 330], [2120, 310], [2320, 250], [2520, 210], [2720, 190]], 0.08, 6);
  far.path(poly(cliff.concat([[2720, H + 40]])), far.vert([[0, "#a2b9ad"], [0.7, "#b7c9be"], [1, "#d6e0d8"]], 200, 1100));
  let streaks = "";
  for (let i = 0; i < 26; i++) {
    const x = 1880 + r() * 800, y = yAt(cliff, x) + 30 + r() * 200;
    streaks += box(x, y, 3 + r() * 5, 120 + r() * 380);
  }
  far.path(streaks, "#93ab9f", ` opacity=".35"`);
  far.add(canopy(r, cliff.filter(([, y], i) => i % 4 === 0 && y < 420).map(([x, y]) => [x, y + 14]), 30, ["#8fa99a", "#9db5a6", "#b2c7b8", "#b2c7b8"], { light: [-0.4, -0.9] }));
  waterfall(far, r, 2080, yAt(cliff, 2080) + 18, 1010, 70);
  // The cliff's foot sinks into the lake behind a bank of spray
  far.path(box(1480, 990, W - 1440, H - 950), far.vert([[0, "#c4e1da", 0], [0.06, "#c4e1da", 0.95], [1, "#b2d6cf", 0.95]], 990, H));
  far.path(glints(r, 50, 1500, W, 1010, 1180), "#ffffff", ` opacity=".45"`);
  far.band(900, 1100, "#ffffff", 0.6);
  far.save();

  r = rng(633);
  const mid = new Layer("day-1-mid");
  // Both banks slope down into the water below the terrace floor, so no edge shows through the glass
  jungleRidge(mid, r, [[-140, 1130], [160, 1030], [460, 1050], [760, 1140], [1000, 1260], [1100, 1460]], NEAR_JUNGLE, 34);
  jungleRidge(mid, r, [[1420, 1460], [1560, 1250], [1760, 1140], [2000, 1050], [2300, 1010], [2720, 990]], NEAR_JUNGLE, 34);
  let palms = "";
  for (const [x, top, lean] of [[120, 470, 40], [320, 580, -30], [2170, 430, -50], [2340, 330, 30], [2480, 500, 60]]) {
    palms += palm(r, [x, 1160], [x + lean, top], { ...SLIM_PALM, bow: lean * 0.5 });
  }
  mid.add(`<g filter="${mid.blur(1.2)}">${palms}</g>`);
  mid.band(1060, 1200, "#f4f1ea", 0.55);
  mid.save();

  r = rng(644);
  const near = new Layer("day-1-near");
  near.path(box(-40, 1196, W + 80, H), near.vert([[0, "#f1ebe2"], [1, "#e2d8ca"]], 1196, H));
  near.add(`<path d="${floorLines(1196, H, 1280, 700, 360, [1250, 1330])}" stroke="#d6cbbb" stroke-width="2" opacity=".6"/>`);
  near.path(box(-40, 1196, W + 80, 70), near.vert([[0, "#ffffff", 0.55], [1, "#ffffff", 0]], 1196, 1266));
  near.path(box(-40, 1040, W + 80, 146), "#ffffff", ` opacity=".14"`);
  let glass = "";
  for (let x = 120; x < W; x += 640) glass += box(x, 1040, 3, 146);
  for (const x of [700, 1500, 2200]) glass += poly([[x, 1040], [x + 60, 1040], [x - 30, 1186], [x - 90, 1186]]);
  near.path(glass, "#ffffff", ` opacity=".35"`);
  near.path(box(-40, 1032, W + 80, 9), "#d2c9bb").path(box(-40, 1182, W + 80, 18), "#ddd5c8");
  // A white pillar on the left, its shadow on the floor
  near.add(`<g filter="${near.blur(10)}" opacity=".18"><path d="${poly([[290, 1196], [560, 1196], [1100, H + 40], [290, H + 40]])}" fill="#8a7a66"/></g>`);
  near.path(box(-40, -40, 330, 1240), near.horiz([[0, "#e5ddd1"], [1, "#faf7f2"]], -40, 290));
  pot(near, 170, 1420, 230, 300);
  near.add(buckthorn(r, 170, 1124, 620, 7));
  pot(near, 450, 1330, 150, 120);
  near.add(aloe(r, 450, 1214, 220));
  // A long planter on the right
  near.puff(2380, 1400, 330, 26, "#7d6f5f", 0.35);
  near.add(buckthorn(r, 2290, 1260, 460, 6));
  near.add(aloe(r, 2480, 1258, 210) + aloe(r, 2180, 1262, 150));
  near.path(box(2120, 1250, 520, 150), near.vert([[0, "#fbf8f3"], [1, "#e4dccf"]], 1250, 1400)).path(box(2120, 1250, 520, 8), "#ffffff");
  near.save();

  r = rng(655);
  const front = new Layer("day-1-front");
  front.path(box(-40, -40, W + 80, 150), front.vert([[0, "#e5dccf"], [1, "#f4efe7"]], -40, 110)).path(box(-40, 104, W + 80, 10), "#d9cfc0");
  for (const x of [640, 1280, 1920]) front.puff(x, 112, 90, 30, "#fff1d6", 0.8);
  front.add(`<g filter="${front.blur(7)}" opacity=".9">${palm(r, null, [2640, -80], { ...SLIM_PALM, dark: "#4f7550", leaf: "#6f9763", len: 560, fronds: 8, fan: 1.3, tilt: -1.1 })}</g>`);
  front.puff(2500, 60, 600, 420, "#fffaf0", 0.45);
  front.save();
}

// 2 · The gallery: a quiet room with a tall window onto a waterfall, sun pooling on the oak floor.
function day2() {
  let r = rng(711);
  const sky = new Layer("day-2-sky");
  softSky(sky, r, { sun: [380, 120], rays: [0.45, 1.2], clouds: [[600, 700, 900, 260], [1800, 820, 800, 240]], wisps: [[700, 260, 380, 4]] });
  sky.save();

  // Outside, seen through the window: a fern-hung cliff and a tall fall into a pool
  r = rng(722);
  const far = new Layer("day-2-far");
  jungleRidge(far, r, [[-140, 760], [300, 620], [700, 700], [1100, 820]], HAZE_JUNGLE, 30);
  const cliff = rock(r, [[-140, 1200], [-140, 140], [80, 120], [240, 170], [360, 230], [520, 214], [700, 290], [860, 440], [980, 640], [1020, 1200]], 0.08, 6);
  far.path(poly(cliff), far.vert([[0, "#9db4a6"], [0.6, "#aec3b5"], [1, "#cbd8ce"]], 120, 1200));
  let streaks = "";
  for (let i = 0; i < 30; i++) {
    const x = r() * 960;
    streaks += box(x, 250 + r() * 400, 3 + r() * 6, 150 + r() * 400);
  }
  far.path(streaks, "#8ea596", ` opacity=".3"`);
  far.add(canopy(r, cliff.filter(([, y], i) => i % 4 === 0 && y < 300).map(([x, y]) => [x, y + 10]), 34, ["#86a28f", "#94af9b", "#aac3ae", "#aac3ae"], { light: [0.4, -0.9] }));
  far.add(`<rect x="-40" y="1060" width="1100" height="400" fill="${far.vert([[0, "#cfe7e1"], [1, "#a9d3cb"]], 1060, 1300)}"/>`);
  waterfall(far, r, 440, 214, 1070, 110);
  far.save();

  r = rng(733);
  const mid = new Layer("day-2-mid");
  mid.add(`<g filter="${mid.blur(1)}">${palm(r, [790, 1260], [730, 300], { ...SLIM_PALM, len: 300 })}</g>`);
  let ferns = "";
  for (let i = 0; i < 40; i++) ferns += leafPath(60 + r() * 760, 1180, -Math.PI / 2 + (r() - 0.5) * 2.2, 90 + r() * 110, 14 + r() * 8, (r() - 0.5) * 40);
  mid.path(ferns, mid.vert([[0, "#9dbb92"], [1, "#6f9070"]], 980, 1180));
  mid.save();

  r = rng(744);
  const near = new Layer("day-2-near");
  near.path(box(-40, -40, W + 80, 1300) + box(150, 170, 630, 980), near.horiz(WALL), ` fill-rule="evenodd"`);
  near.path(poly([[150, 170], [190, 200], [190, 1120], [150, 1150]]), "#e2d9cc");
  near.path(box(150, 170, 630, 980) + box(164, 184, 602, 952), "#6f6a62", ` fill-rule="evenodd"`).path(box(458, 184, 14, 952), "#6f6a62");
  near.path(poly([[200, 184], [330, 184], [164, 520], [164, 300]]) + poly([[560, 184], [620, 184], [472, 470], [472, 360]]), "#ffffff", ` opacity=".14"`);
  near.path(box(120, 1146, 700, 26), "#fbf8f3").puff(470, 1180, 380, 14, "#7d6f5f", 0.3);
  // Oak floor, the window's reflection, and a pool of sun
  near.path(box(-40, 1262, W + 80, H), near.vert(OAK, 1262, H)).path(box(-40, 1248, W + 80, 16), "#f6f1ea");
  near.add(`<path d="${floorLines(1264, H, 1280, 900, 150)}" stroke="#bf9d73" stroke-width="2" opacity=".45"/>`);
  near.path(poly([[160, 1264], [770, 1264], [880, H], [80, H]]), near.vert([[0, "#ffffff", 0.45], [1, "#ffffff", 0]], 1264, H));
  near.add(`<g filter="${near.blur(4)}" opacity=".55"><path d="${poly([[900, 1290], [1230, 1290], [1640, H + 20], [1140, H + 20]]) + poly([[1255, 1290], [1560, 1290], [2050, H + 20], [1670, H + 20]])}" fill="#fff4dc"/></g>`);
  // Sideboard with buckthorn in a glass vase, an aloe, a few books and a print
  near.path(box(2020, 470, 360, 450), "#ddd3c5").path(box(2040, 490, 320, 410), near.vert([[0, "#eef0ea"], [1, "#e2e6dc"]], 490, 900));
  near.path(area(wave(r, 760, [[30, 300], [10, 90]], 12, 2040, 2360), 900), "#b9c9b4").path(circle(2270, 620, 46), "#f2dcb8");
  near.puff(2230, 1262, 340, 18, "#7d6f5f", 0.35);
  near.path(box(1960, 1060, 560, 190), near.vert(OAK, 1060, 1250)).path(box(1960, 1060, 560, 8), "#f0dcbe");
  near.path(box(2238, 1076, 4, 160) + box(1990, 1250, 10, 12) + box(2480, 1250, 10, 12), "#b8966c");
  near.add(buckthorn(r, 2080, 980, 500, 7));
  near.path(`M2040,1060V940Q2040,900 2080,900Q2120,900 2120,940V1060Z`, "#ffffff", ` opacity=".35"`).path(box(2044, 990, 72, 70), "#dfeee9", ` opacity=".5"`);
  near.path(box(2180, 1040, 150, 20), "#d9cdb8").path(box(2190, 1022, 130, 18), "#b9c4ad").path(box(2184, 1006, 140, 16), "#ece4d4");
  pot(near, 2410, 1060, 130, 100);
  near.add(aloe(r, 2410, 962, 180));
  near.save();

  r = rng(755);
  const front = new Layer("day-2-front");
  shafts(front, [[[160, 170], [780, 170], [1700, H], [900, H]], [[300, 170], [600, 170], [1200, H], [800, H]]], 0.2);
  let leaves = "";
  for (let i = 0; i < 7; i++) leaves += leafPath(2620, 1500, -1.7 - i * 0.22, 420 + r() * 180, 80 + r() * 30, -50);
  front.add(`<g filter="${front.blur(9)}" opacity=".85"><path d="${leaves}" fill="#5f8661"/></g>`);
  front.save();
}

// 3 · The study: timber ceiling, sheer curtains drawn back, the sea and a headland fall outside.
function day3() {
  let r = rng(811);
  const sky = new Layer("day-3-sky");
  softSky(sky, r, { sun: [1880, 150], rays: [1.95, 2.7], clouds: [[1050, 830, 900, 280], [1760, 860, 520, 180]], wisps: [[900, 360, 420, -3]] });
  sky.save();

  r = rng(822);
  const far = new Layer("day-3-far");
  far.add(`<rect x="-40" y="890" width="${W + 80}" height="${H - 850}" fill="${far.vert([[0, "#a7d3cf"], [0.5, "#bfe2db"], [1, "#d9ede4"]], 890, 1080)}"/>`);
  far.path(glints(r, 120, 400, 2200, 896, 1070, 1880, 300), "#ffffff", ` opacity=".6"`);
  far.path(poly(rock(r, [[1460, 896], [1560, 868], [1700, 860], [1800, 880], [1860, 896]], 0.1, 4)), "#b4cbc5");
  const head = rock(r, [[300, 1000], [380, 760], [520, 660], [700, 640], [860, 690], [960, 800], [1010, 1000]], 0.1, 6);
  far.path(poly(head), far.vert([[0, "#93ae9e"], [1, "#b7cbbd"]], 640, 1000));
  far.add(canopy(r, head.filter((_, i) => i % 3 === 0 && head[i][1] < 860).map(([x, y]) => [x, y + 10]), 26, ["#88a492", "#96b09f", "#aec5b3", "#aec5b3"], { light: [0.6, -0.8] }));
  waterfall(far, r, 900, 730, 980, 34);
  far.band(860, 920, "#f6f6f0", 0.7);
  far.save();

  r = rng(833);
  const mid = new Layer("day-3-mid");
  const beach = wave(r, 1060, [[8, 700], [3, 200]]);
  mid.path(area(beach), mid.vert([[0, "#f4ede0"], [1, "#ece2d0"]], 1050, 1180));
  mid.add(`<path d="${line(beach)}" fill="none" stroke="#ffffff" stroke-width="5" opacity=".9"/>`);
  let palms = "";
  for (const [x, top, lean] of [[600, 430, 30], [740, 580, -20], [1880, 400, -30], [1990, 540, 40]]) palms += palm(r, [x, 1070], [x + lean, top], { ...SLIM_PALM, bow: lean * 0.4 });
  mid.add(`<g filter="${mid.blur(1)}">${palms}${buckthorn(r, 1720, 1070, 230, 6)}${aloe(r, 820, 1072, 150)}${aloe(r, 1640, 1072, 120)}</g>`);
  mid.save();

  r = rng(844);
  const near = new Layer("day-3-near");
  near.path(box(-40, 1170, W + 80, H), near.vert([[0, "#f2ede5"], [1, "#dfd5c6"]], 1170, H));
  near.add(`<path d="${floorLines(1170, H, 1280, 900, 340, [1215, 1280, 1370])}" stroke="#d3c8b7" stroke-width="2" opacity=".55"/>`);
  near.path(poly([[520, 1170], [2040, 1170], [2320, H], [240, H]]), near.vert([[0, "#ffffff", 0.6], [1, "#ffffff", 0]], 1170, H));
  near.path(poly([[760, 1250], [1800, 1250], [2060, H + 10], [500, H + 10]]), "#e9e0d0").path(poly([[790, 1262], [1770, 1262], [2010, H + 10], [550, H + 10]]), "#efe8dc");
  // Walls either side of the opening
  near.path(box(-40, -40, 520, 1222), near.horiz([[0, "#e7dfd3"], [1, "#f7f3ec"]], -40, 480)).path(box(470, -40, 14, 1222), "#ddd3c4");
  near.path(box(2080, -40, 600, 1222), near.horiz([[0, "#f7f3ec"], [1, "#e7dfd3"]], 2080, 2640)).path(box(2076, -40, 14, 1222), "#ddd3c4");
  // Shelves: light oak, ceramics, a few books, warm light under each shelf
  near.path(box(2160, 380, 400, 800), "#efe6d8");
  let boards = "", books = "", ceramics = "";
  for (let s = 0; s < 4; s++) {
    const y = 380 + s * 200;
    boards += box(2160, y + 186, 400, 14);
    near.puff(2360, y + 18, 190, 26, "#ffe7bf", 0.6);
    let x = 2190;
    while (x < 2520) {
      if (r() < 0.25) {
        ceramics += `M${f(x + 14)},${y + 186}q-16,-34 4,-62v-24h18v24q20,28 4,62Z`;
        x += 62;
        continue;
      }
      if (r() < 0.15) { x += 40; continue; }
      const w = 14 + r() * 14, h = 100 + r() * 60;
      near.path(box(x, y + 186 - h, w, h), pick(r, ["#e9e2d4", "#d6c8b1", "#b9c2ae", "#ddd0ba", "#c8b79c"]));
      x += w + 2;
    }
  }
  near.path(ceramics, "#fbf8f2").path(boards, "#d3b58c").path(box(2150, 370, 14, 820) + box(2556, 370, 14, 820), "#d3b58c");
  near.add(buckthorn(r, 260, 1060, 620, 8));
  near.path(`M215,1240V1080Q215,1050 260,1050Q305,1050 305,1080V1240Z`, near.horiz([[0, "#ded6c9"], [0.4, "#ffffff"], [1, "#d3cabc"]], 215, 305)).puff(260, 1242, 80, 12, "#7d6f5f", 0.35);
  // Sheer curtains, drawn back to both sides of the opening
  const sheer = near.horiz([[0, "#ffffff", 0.5], [0.5, "#ffffff", 0.88], [1, "#ffffff", 0.5]], 0, 46, ' spreadMethod="reflect"');
  near.path(`M484,190H660Q620,700 640,1180H484Z`, sheer).path(`M1920,190H2076V1180H1900Q1930,700 1920,190Z`, sheer);
  near.save();

  r = rng(855);
  const front = new Layer("day-3-front");
  front.path(box(-40, -40, W + 80, 236), front.vert([[0, "#d6bb94"], [1, "#e6d1b2"]], -40, 196));
  let slats = "";
  for (let x = 20; x < W; x += 46) slats += box(x, -40, 3, 236);
  front.path(slats, "#c4a47b", ` opacity=".5"`).path(box(-40, 192, W + 80, 40), "#f6f1e9");
  front.puff(1280, 236, 1700, 34, "#ffe7bf", 0.75);
  shafts(front, [[[2040, 190], [2076, 190], [1500, H], [1200, H]], [[1600, 190], [1900, 190], [1300, H], [900, H]]], 0.16);
  // Desk: one light-oak slab with a waterfall edge, a slim monitor, a small aloe
  front.puff(860, 1470, 700, 30, "#6d5c48", 0.3);
  front.path(poly([[300, 1300], [1420, 1300], [1460, 1340], [260, 1340]]), front.vert(OAK, 1300, 1340));
  front.path(box(260, 1340, 1200, 26), "#c09c72").path(box(260, 1340, 34, 160), front.horiz([[0, "#c09c72"], [1, "#d8bc95"]], 260, 294));
  front.path(box(1300, 1366, 26, 140), "#b9966c");
  front.path(box(900, 1070, 360, 210), "#e9e9eb").path(box(910, 1080, 340, 190), front.vert([[0, "#e6eef2"], [1, "#c9d7df"]], 1080, 1270));
  front.path(box(940, 1110, 120, 10) + box(940, 1130, 200, 8) + box(940, 1146, 160, 8) + box(1100, 1180, 120, 70), "#ffffff", ` opacity=".7"`);
  front.path(poly([[1050, 1280], [1110, 1280], [1124, 1304], [1036, 1304]]), "#d9d9dc").path(box(1000, 1300, 160, 5), "#cfcfd2");
  front.path(poly([[1200, 1290], [1360, 1290], [1380, 1302], [1180, 1302]]), "#e2e2e5");
  pot(front, 520, 1302, 80, 66);
  front.add(aloe(r, 520, 1240, 110));
  front.path(`M650,1302v-44h40v44Z`, "#f8f5ef").path(oval(670, 1258, 20, 5), "#c7a27c");
  front.save();
}

// ======================= Markup =======================

const SETS = { night: [night1, night2, night3], day: [day1, day2, day3] };
const LAYERS = ["sky", "far", "mid", "near", "front"];
const SPEEDS = [0.6, 0.45, 0.32, 0.18, 0];
// Where each scene's interest lies (0 = left edge, 1 = right edge). Narrow screens only see a slice
// of the 16:9 art, so scene.js aims that slice here instead of at the calm middle.
const FOCUS = { night: [0.8, 0.5, 0.8], day: [0.8, 0.18, 0.5] };

// Whatever file a layer currently has: your own image first, then the generated SVG.
function fileFor(base) {
  return [...RASTER, "svg"].map((ext) => `${base}.${ext}`).find((name) => fs.existsSync(path.join(OUT, name)));
}

// A layer's motion overlay is used only with the generated SVG it belongs to.
function motionFor(base, file) {
  const fx = `${base}-fx.svg`;
  return file === `${base}.svg` && fs.readFileSync(path.join(OUT, file), "utf8").includes(MARK) && fs.existsSync(path.join(OUT, fx)) ? fx : null;
}

// Every image waits in data-href: scene.js loads the theme you are looking at, scene by scene.
function layer(base, speed) {
  const file = fileFor(base), fx = motionFor(base, file);
  const img = (name, extra = "") => `<image data-href="assets/scene/${name}"${extra} width="${W}" height="${H}"/>`;
  return `<div class="scene-layer" data-speed="${speed}"><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="xMidYMax slice">` +
    img(file) + (fx ? img(fx, " data-motion") : "") + `</svg></div>`;
}

function sceneMarkup(indent) {
  const i = (n) => "\n" + indent + "    ".repeat(n);
  let out = `<!-- scene:start (generated by tools/gen-scene.mjs) -->${i(0)}<div class="scene" aria-hidden="true">`;
  for (let k = 0; k < 3; k++) {
    out += `${i(1)}<div class="scene-chapter${k === 0 ? " is-shown" : ""}" data-chapter="${k + 1}">`;
    for (const set of Object.keys(SETS)) {
      out += `${i(2)}<div class="scene-set scene-${set}" data-set="${set}" data-focus="${FOCUS[set][k]}">`;
      LAYERS.forEach((name, n) => {
        const base = `${set}-${k + 1}-${name}`;
        if (fileFor(base)) out += i(3) + layer(base, SPEEDS[n]);
      });
      out += `${i(2)}</div>`;
    }
    out += `${i(1)}</div>`;
  }
  return out + `${i(1)}<canvas class="scene-fx"></canvas>${i(1)}<div class="scene-dim"></div>${i(0)}</div>${i(0)}<!-- scene:end -->`;
}

// Clear out generated layers that no longer belong to any scene.
const current = new Set(Object.keys(SETS).flatMap((set) => [1, 2, 3].flatMap((k) => LAYERS.flatMap((n) => [`${set}-${k}-${n}.svg`, `${set}-${k}-${n}-fx.svg`]))));
for (const old of fs.readdirSync(OUT)) {
  const file = path.join(OUT, old);
  if (old.endsWith(".svg") && !current.has(old) && fs.readFileSync(file, "utf8").includes(MARK)) fs.unlinkSync(file);
}

for (const scenes of Object.values(SETS)) scenes.forEach((draw) => draw());

const indexPath = path.join(REPO, "index.html");
const html = fs.readFileSync(indexPath, "utf8");
const re = /^([ \t]*)<!-- scene:start[\s\S]*?<!-- scene:end -->/m;
const m = html.match(re);
if (!m) throw new Error("scene markers missing in index.html");
fs.writeFileSync(indexPath, html.replace(re, m[1] + sceneMarkup(m[1])));
console.log("index.html: scene markup updated");
